### ISSUE TITLE
Comparison TensorFlow Lite

### ISSUE THREAD

**Issue by jonalm** [ai-techsystems/deepC#138]
Hi there, 

Sorry in advance if these types of questions are inappropriate here. (Please point me to another forum, if that exist.) 

I have to decide upon a framework for running an ONNX-model on an x86 micro-controller. I am curious to know the pros/cons of using deepC versus TensorFlow Lite or other alternative frameworks?

**Comment by srohit0** [comment]
deepC is better, faster and frugal on MCUs compared to TFLM.

try deepC on http://www.tinyml.studio/ without downloading/compiling

**Comment by jonalm** [comment]
That sounds good, thanks for the link.

**Comment by jonalm** [comment]
@srohit0 Do you happen to know of any blogs or similar which benchmark/compare performance?

**Comment by srohit0** [comment]
Yes, they are not publicly released.
